version: '3'
services:
  node_graphql_db:
    image: postgres:latest
    container_name: node_graphql_development_db
    volumes:
      - ./docker/postgres/multipledbs.sh:/docker-entrypoint-initdb.d/multipledbs.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES="development","testing"
      - POSTGRES_PASSWORD=zAcPeAh6BbYRQ
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'